# Setup
title:               Suryaa Rajinikanth
tagline:             ''
description:         ''
url:                 https://5ury44.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Suryaa Rajinikanth
  url:               https://linkedin.com/in/5ury44
  email:             suryaa@gatech.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-232465779-2
